### ISSUE TITLE
questions please

### ISSUE THREAD

**Issue by agony09** [martinambrus/TravianZ#37]
Hello, I just wanted to ask if this script still makes so many database queries (400) per page view? Or has something already changed? I noticed with the demo here (the link from this page here) that with 6 online players the pages sometimes take a long time to be set up. Or is that something else planned?
And which PHP version is recommended?
Thanks in advance and best regards

**Comment by martinambrus** [comment]
Yes, the code still makes loads of queries on every automation run. It's not on every page load anymore, as the automation script was updated to run only once at a time and any subsequent page refresh will fetch old data until the old automation script finishes. This said, you can see that page refresh sometimes takes 42ms, other times 2 seconds on the test server.

Also, the test server is running on a shared hosting with the cheapest plan, so its power is limited. This makes is a great test environment to see how optimized the queries and code portions really are at this point. If this was ran on a dedicated host, you would see a much improved performance for sure.

As for PHP version, definitelly PHP 7.2+

**Comment by agony09** [comment]
ok, thanks a lot for this good info.
I am happy that this script is being developed further.
I think I found a small bug in the demo, in the quests when you should change the village name. There is no waiting for the name to be changed. It is just skipped.

**Comment by martinambrus** [comment]
if you already changed the name, this shouldn't happen - did it happen with the original name?

**Comment by agony09** [comment]
yes it happened to the original name. I never changed the name. And the task master just carried on with the next task.
